-- ============================================================
-- SCHEMA: OKW FieldSync Backend for ODEQ 2026 Compliance
-- Database: Oracle 23ai
-- Author: Senior Database Architect
-- Notes: Enforces composite classification, chain of custody,
--        GPS precision, and automated verification status.
-- ============================================================

-- ============================================================
-- 1. SERVICE LINES TABLE (with split ownership & composite classification)
-- ============================================================
CREATE TABLE service_lines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR2(50) UNIQUE NOT NULL,
    -- Ownership split
    system_owned NUMBER(1) NOT NULL CHECK (system_owned IN (0,1)) DEFAULT 1,
    customer_owned NUMBER(1) NOT NULL CHECK (customer_owned IN (0,1)) DEFAULT 0,
    -- Material tracking (ODEQ required)
    service_line_material VARCHAR2(30) CHECK (service_line_material IN ('lead', 'galvanized_requiring_replacement', 'copper', 'plastic', 'unknown', 'non-lead_other')),
    customer_side_material VARCHAR2(30) CHECK (customer_side_material IN ('lead', 'galvanized_requiring_replacement', 'copper', 'plastic', 'unknown', 'non-lead_other', 'not_applicable')),
    -- Composite classification (computed, but stored for audit)
    composite_classification VARCHAR2(50) GENERATED ALWAYS AS (
        CASE
            WHEN system_owned = 1 AND service_line_material = 'lead' THEN 'System_Lead'
            WHEN customer_owned = 1 AND customer_side_material = 'lead' THEN 'Customer_Lead'
            WHEN system_owned = 1 AND service_line_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
            WHEN customer_owned = 1 AND customer_side_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
            ELSE 'Non-Lead_Or_Unknown'
        END
    ) VIRTUAL,
    -- Verification status (initially false, auto-updated by trigger)
    verified_status NUMBER(1) DEFAULT 0 NOT NULL CHECK (verified_status IN (0,1)),
    verified_at TIMESTAMP WITH TIME ZONE,
    verified_by NUMBER,
    -- Location & metadata
    installation_year NUMBER(4) CHECK (installation_year BETWEEN 1800 AND EXTRACT(YEAR FROM SYSTIMESTAMP)),
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT ownership_consistency CHECK (
        (system_owned = 1 OR customer_owned = 1) AND NOT (system_owned = 0 AND customer_owned = 0)
    )
);

COMMENT ON TABLE service_lines IS 'Tracks lead service line inventory with split ownership per ODEQ 2026 standards.';
COMMENT ON COLUMN service_lines.composite_classification IS 'Auto-computed per ODEQ Section 2.2: System_Lead, Customer_Lead, Galvanized_Requiring_Replacement, or Non-Lead_Or_Unknown';

-- ============================================================
-- 2. EVIDENCE TABLE (photos, GPS WGS84, timestamps)
-- ============================================================
CREATE TABLE evidence (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_line_id NUMBER NOT NULL REFERENCES service_lines(id) ON DELETE CASCADE,
    evidence_type VARCHAR2(30) NOT NULL CHECK (evidence_type IN ('photo', 'video', 'document', 'lab_result')),
    photo_uuid RAW(16) DEFAULT SYS_GUID(),
    -- High-precision GPS (WGS84) using Oracle Spatial (SDO_GEOMETRY)
    gps_location SDO_GEOMETRY NOT NULL,
    gps_accuracy_meters NUMBER(6,2),
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
    uploaded_by NUMBER,
    file_hash VARCHAR2(64),
    notes CLOB,
    
    CONSTRAINT photo_uuid_required_for_photos CHECK (
        NOT (evidence_type = 'photo' AND photo_uuid IS NULL)
    )
);

-- Spatial index for GPS queries
CREATE INDEX idx_evidence_gps ON evidence(gps_location) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX idx_evidence_service_line ON evidence(service_line_id);
CREATE INDEX idx_evidence_captured_at ON evidence(captured_at);

COMMENT ON TABLE evidence IS 'Stores photographic evidence with WGS84 GPS per ODEQ sampling rules.';
COMMENT ON COLUMN evidence.gps_location IS 'WGS84 coordinate using Oracle Spatial: SDO_GEOMETRY(2001, 4326, SDO_POINT_TYPE(lon, lat, NULL), NULL, NULL)';

-- ============================================================
-- 3. PFAS SAMPLING TABLE (Chain of Custody + PPE + FRB/EB/TB)
-- ============================================================
CREATE TABLE pfas_sampling (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id VARCHAR2(50) UNIQUE NOT NULL,
    service_line_id NUMBER NOT NULL REFERENCES service_lines(id),
    -- Chain of Custody
    collected_by VARCHAR2(100) NOT NULL,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_by_lab VARCHAR2(100),
    received_at_lab TIMESTAMP WITH TIME ZONE,
    custody_transfer_count NUMBER DEFAULT 1 CHECK (custody_transfer_count >= 1),
    -- Sampling sequence (ODEQ 2026: FRB, EB, TB)
    sample_type VARCHAR2(10) NOT NULL CHECK (sample_type IN ('FRB', 'EB', 'TB', 'regular', 'duplicate', 'rinse_blank')),
    sequence_number NUMBER NOT NULL,
    batch_id VARCHAR2(50),
    -- PPE tracking
    ppe_gloves NUMBER(1) NOT NULL DEFAULT 1 CHECK (ppe_gloves IN (0,1)),
    ppe_booties NUMBER(1) NOT NULL DEFAULT 1 CHECK (ppe_booties IN (0,1)),
    ppe_tyvek_suit NUMBER(1) DEFAULT 0 CHECK (ppe_tyvek_suit IN (0,1)),
    ppe_face_mask NUMBER(1) DEFAULT 1 CHECK (ppe_face_mask IN (0,1)),
    ppe_other VARCHAR2(500),
    -- Sample results
    pfas_picograms_per_liter NUMBER(12,2),
    pfas_compound_tested VARCHAR2(30) CHECK (pfas_compound_tested IN ('PFOA', 'PFOS', 'PFNA', 'PFHxS', 'HFPO-DA', 'full_panel')),
    lab_notes CLOB,
    -- Audit
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT pfas_chain_custody_logic CHECK (
        (received_by_lab IS NOT NULL AND received_at_lab IS NOT NULL) OR 
        (received_by_lab IS NULL AND received_at_lab IS NULL)
    )
);

COMMENT ON TABLE pfas_sampling IS 'Implements PFAS sampling with Chain of Custody and FRB/EB/TB sequencing per ODEQ 2026.';

-- ============================================================
-- 4. AUDIT LOGS TABLE (bulletproof paper trail)
-- ============================================================
CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(100) NOT NULL,
    record_id NUMBER NOT NULL,
    action VARCHAR2(10) NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_data JSON,
    new_data JSON,
    changed_by VARCHAR2(100) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500)
);

CREATE INDEX idx_audit_table_record ON audit_logs(table_name, record_id);
CREATE INDEX idx_audit_changed_at ON audit_logs(changed_at);

COMMENT ON TABLE audit_logs IS 'Immutable audit trail for all compliance-critical changes.';

-- ============================================================
-- 5. ORACLE 23ai JSON AUDIT TRIGGER FUNCTION
-- ============================================================
CREATE OR REPLACE TRIGGER trg_audit_service_lines
AFTER INSERT OR UPDATE OR DELETE ON service_lines
FOR EACH ROW
DECLARE
    v_old_json JSON;
    v_new_json JSON;
    v_action VARCHAR2(10);
    v_changed_by VARCHAR2(100) := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'system');
    v_ip VARCHAR2(45) := SYS_CONTEXT('USERENV', 'IP_ADDRESS');
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_new_json := JSON( :NEW );
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_old_json := JSON( :OLD );
        v_new_json := JSON( :NEW );
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_old_json := JSON( :OLD );
    END IF;
    
    INSERT INTO audit_logs (table_name, record_id, action, old_data, new_data, changed_by, ip_address)
    VALUES ('service_lines', COALESCE(:NEW.id, :OLD.id), v_action, v_old_json, v_new_json, v_changed_by, v_ip);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_evidence
AFTER INSERT OR UPDATE OR DELETE ON evidence
FOR EACH ROW
DECLARE
    v_old_json JSON;
    v_new_json JSON;
    v_action VARCHAR2(10);
    v_changed_by VARCHAR2(100) := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'system');
    v_ip VARCHAR2(45) := SYS_CONTEXT('USERENV', 'IP_ADDRESS');
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_new_json := JSON( :NEW );
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_old_json := JSON( :OLD );
        v_new_json := JSON( :NEW );
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_old_json := JSON( :OLD );
    END IF;
    
    INSERT INTO audit_logs (table_name, record_id, action, old_data, new_data, changed_by, ip_address)
    VALUES ('evidence', COALESCE(:NEW.id, :OLD.id), v_action, v_old_json, v_new_json, v_changed_by, v_ip);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_pfas_sampling
AFTER INSERT OR UPDATE OR DELETE ON pfas_sampling
FOR EACH ROW
DECLARE
    v_old_json JSON;
    v_new_json JSON;
    v_action VARCHAR2(10);
    v_changed_by VARCHAR2(100) := COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'system');
    v_ip VARCHAR2(45) := SYS_CONTEXT('USERENV', 'IP_ADDRESS');
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_new_json := JSON( :NEW );
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_old_json := JSON( :OLD );
        v_new_json := JSON( :NEW );
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_old_json := JSON( :OLD );
    END IF;
    
    INSERT INTO audit_logs (table_name, record_id, action, old_data, new_data, changed_by, ip_address)
    VALUES ('pfas_sampling', COALESCE(:NEW.id, :OLD.id), v_action, v_old_json, v_new_json, v_changed_by, v_ip);
END;
/

-- ============================================================
-- 6. AUTOMATED VERIFICATION STATUS LOGIC (Section 2.3)
--    ODEQ 2026: Service Line becomes 'Verified' ONLY IF:
--    a) Photographic evidence with GPS accuracy ≤ 2 meters
--    b) IF lead/galvanized: PFAS FRB sample exists with lab receipt
--    c) System-owned material confirmed (not 'unknown')
-- ============================================================
CREATE OR REPLACE TRIGGER trg_enforce_verified_status
BEFORE INSERT OR UPDATE ON service_lines
FOR EACH ROW
DECLARE
    v_has_photo_evidence NUMBER(1) := 0;
    v_has_pfas_frb NUMBER(1) := 0;
    v_material_confirmed NUMBER(1) := 0;
    v_composite VARCHAR2(50);
BEGIN
    -- Store composite for logic (since :NEW.composite_classification is virtual)
    v_composite := CASE
        WHEN :NEW.system_owned = 1 AND :NEW.service_line_material = 'lead' THEN 'System_Lead'
        WHEN :NEW.customer_owned = 1 AND :NEW.customer_side_material = 'lead' THEN 'Customer_Lead'
        WHEN :NEW.system_owned = 1 AND :NEW.service_line_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
        WHEN :NEW.customer_owned = 1 AND :NEW.customer_side_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
        ELSE 'Non-Lead_Or_Unknown'
    END;
    
    -- Condition (a): Photo evidence with GPS accuracy <= 2 meters
    -- Note: This query runs per row; for bulk operations consider alternative approach
    BEGIN
        SELECT COUNT(*) INTO v_has_photo_evidence
        FROM evidence
        WHERE service_line_id = :NEW.id
        AND evidence_type = 'photo'
        AND gps_accuracy_meters <= 2
        AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_has_photo_evidence := 0;
    END;
    
    -- Condition (b): If lead/galvanized, require PFAS FRB sample with lab receipt
    IF v_composite IN ('System_Lead', 'Customer_Lead', 'Galvanized_Requiring_Replacement') THEN
        BEGIN
            SELECT COUNT(*) INTO v_has_pfas_frb
            FROM pfas_sampling
            WHERE service_line_id = :NEW.id
            AND sample_type = 'FRB'
            AND received_by_lab IS NOT NULL
            AND ROWNUM = 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_has_pfas_frb := 0;
        END;
    ELSE
        v_has_pfas_frb := 1;
    END IF;
    
    -- Condition (c): System-owned material confirmed not 'unknown'
    IF :NEW.system_owned = 0 OR :NEW.service_line_material != 'unknown' THEN
        v_material_confirmed := 1;
    END IF;
    
    -- Set verification status
    IF v_has_photo_evidence = 1 AND v_has_pfas_frb = 1 AND v_material_confirmed = 1 THEN
        :NEW.verified_status := 1;
        :NEW.verified_at := SYSTIMESTAMP;
    ELSE
        :NEW.verified_status := 0;
        :NEW.verified_at := NULL;
        :NEW.verified_by := NULL;
    END IF;
    
    :NEW.last_updated := SYSTIMESTAMP;
END;
/

-- ============================================================
-- 7. PFAS SEQUENCE ORDER CONSTRAINT (Trigger-based)
--    Enforces FRB/EB/TB precede regular samples in same batch
-- ============================================================
CREATE OR REPLACE TRIGGER trg_check_pfas_sequence_order
BEFORE INSERT OR UPDATE ON pfas_sampling
FOR EACH ROW
DECLARE
    v_has_regular_before NUMBER(1) := 0;
BEGIN
    IF :NEW.batch_id IS NOT NULL AND :NEW.sample_type IN ('FRB', 'EB', 'TB') THEN
        BEGIN
            SELECT COUNT(*) INTO v_has_regular_before
            FROM pfas_sampling
            WHERE batch_id = :NEW.batch_id
            AND sample_type = 'regular'
            AND sequence_number < :NEW.sequence_number
            AND ROWNUM = 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_has_regular_before := 0;
        END;
        
        IF v_has_regular_before = 1 THEN
            RAISE_APPLICATION_ERROR(-20001, 'FRB, EB, or TB must precede regular samples in sequence order per ODEQ 2026');
        END IF;
    END IF;
END;
/

-- ============================================================
-- 8. ORACLE SPATIAL METADATA SETUP (Required for SDO_GEOMETRY)
-- ============================================================
INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES (
    'EVIDENCE',
    'GPS_LOCATION',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.0000001),
        SDO_DIM_ELEMENT('Latitude', -90, 90, 0.0000001)
    ),
    4326  -- WGS84
);

-- ============================================================
-- 9. ADDITIONAL INDEXES FOR COMPLIANCE QUERIES
-- ============================================================
CREATE INDEX idx_service_lines_composite ON service_lines(composite_classification, verified_status);
CREATE INDEX idx_pfas_batch_sequence ON pfas_sampling(batch_id, sequence_number);
CREATE INDEX idx_evidence_gps_accuracy ON evidence(gps_accuracy_meters);

-- ============================================================
-- 10. HELPER FUNCTION FOR GPS POINT CREATION
-- ============================================================
CREATE OR REPLACE FUNCTION make_gps_point(lon IN NUMBER, lat IN NUMBER)
RETURN SDO_GEOMETRY DETERMINISTIC
IS
BEGIN
    RETURN SDO_GEOMETRY(2001, 4326, SDO_POINT_TYPE(lon, lat, NULL), NULL, NULL);
END;
/

-- ============================================================
-- 11. SAMPLE INSERT DEMO (commented, for reference only)
-- ============================================================
/*
-- Enable client identifier for audit
BEGIN
    DBMS_SESSION.SET_IDENTIFIER('inspector_jones');
END;
/

-- Insert a service line
INSERT INTO service_lines (asset_id, system_owned, customer_owned, service_line_material, customer_side_material, installation_year)
VALUES ('SL-1001', 1, 0, 'lead', 'not_applicable', 1950);

-- Add evidence with GPS (using helper function)
INSERT INTO evidence (service_line_id, evidence_type, gps_location, gps_accuracy_meters, captured_at)
VALUES (1, 'photo', make_gps_point(-122.4194, 37.7749), 1.5, SYSTIMESTAMP);

-- PFAS FRB sample
INSERT INTO pfas_sampling (sample_id, service_line_id, collected_by, collected_at, sample_type, sequence_number, batch_id, ppe_gloves)
VALUES ('PFAS-FRB-001', 1, 'Sampler A', SYSTIMESTAMP, 'FRB', 1, 'BATCH-001', 1);

-- Verify status (should auto-update to 1)
SELECT asset_id, composite_classification, verified_status FROM service_lines WHERE asset_id = 'SL-1001';
*/