SET DEFINE OFF
SET ECHO ON

-- ============================================================
-- SCHEMA: OKW FieldSync Backend for ODEQ 2026 Compliance
-- Database: Oracle 23ai
-- ============================================================

-- ============================================================
-- 1. SERVICE LINES TABLE
-- ============================================================
CREATE TABLE service_lines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR2(50) UNIQUE NOT NULL,
    system_owned NUMBER(1) DEFAULT 1 NOT NULL CHECK (system_owned IN (0,1)),
    customer_owned NUMBER(1) DEFAULT 0 NOT NULL CHECK (customer_owned IN (0,1)),
    service_line_material VARCHAR2(30) CHECK (service_line_material IN ('lead','galvanized_requiring_replacement','copper','plastic','unknown','non-lead_other')),
    customer_side_material VARCHAR2(30) CHECK (customer_side_material IN ('lead','galvanized_requiring_replacement','copper','plastic','unknown','non-lead_other','not_applicable')),
    composite_classification VARCHAR2(50) GENERATED ALWAYS AS (
        CASE
            WHEN system_owned = 1 AND service_line_material = 'lead' THEN 'System_Lead'
            WHEN customer_owned = 1 AND customer_side_material = 'lead' THEN 'Customer_Lead'
            WHEN system_owned = 1 AND service_line_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
            WHEN customer_owned = 1 AND customer_side_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
            ELSE 'Non-Lead_Or_Unknown'
        END
    ) VIRTUAL,
    verified_status NUMBER(1) DEFAULT 0 NOT NULL CHECK (verified_status IN (0,1)),
    verified_at TIMESTAMP WITH TIME ZONE,
    verified_by NUMBER,
    installation_year NUMBER(4) CHECK (installation_year BETWEEN 1800 AND 2100),
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT ownership_consistency CHECK (
        (system_owned = 1 OR customer_owned = 1)
        AND NOT (system_owned = 0 AND customer_owned = 0)
    )
);

COMMENT ON TABLE service_lines IS 'Tracks lead service line inventory with split ownership per ODEQ 2026 standards.';

-- ============================================================
-- 2. EVIDENCE TABLE
-- ============================================================
CREATE TABLE evidence (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_line_id NUMBER NOT NULL REFERENCES service_lines(id) ON DELETE CASCADE,
    evidence_type VARCHAR2(30) NOT NULL CHECK (evidence_type IN ('photo','video','document','lab_result')),
    photo_uuid RAW(16) DEFAULT SYS_GUID(),
    gps_location SDO_GEOMETRY NOT NULL,
    gps_accuracy_meters NUMBER(6,2),
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    uploaded_by NUMBER,
    file_hash VARCHAR2(64),
    notes CLOB,
    CONSTRAINT photo_uuid_required_for_photos CHECK (
        NOT (evidence_type = 'photo' AND photo_uuid IS NULL)
    )
);

CREATE INDEX idx_evidence_service_line ON evidence(service_line_id);
CREATE INDEX idx_evidence_captured_at ON evidence(captured_at);
CREATE INDEX idx_evidence_gps_accuracy ON evidence(gps_accuracy_meters);

COMMENT ON TABLE evidence IS 'Stores photographic evidence with WGS84 GPS per ODEQ sampling rules.';

-- ============================================================
-- 3. PFAS SAMPLING TABLE
-- ============================================================
CREATE TABLE pfas_sampling (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id VARCHAR2(50) UNIQUE NOT NULL,
    service_line_id NUMBER NOT NULL REFERENCES service_lines(id),
    collected_by VARCHAR2(100) NOT NULL,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_by_lab VARCHAR2(100),
    received_at_lab TIMESTAMP WITH TIME ZONE,
    custody_transfer_count NUMBER DEFAULT 1 CHECK (custody_transfer_count >= 1),
    sample_type VARCHAR2(15) NOT NULL CHECK (sample_type IN ('FRB','EB','TB','regular','duplicate','rinse_blank')),
    sequence_number NUMBER NOT NULL,
    batch_id VARCHAR2(50),
    ppe_gloves NUMBER(1) DEFAULT 1 NOT NULL CHECK (ppe_gloves IN (0,1)),
    ppe_booties NUMBER(1) DEFAULT 1 NOT NULL CHECK (ppe_booties IN (0,1)),
    ppe_tyvek_suit NUMBER(1) DEFAULT 0 CHECK (ppe_tyvek_suit IN (0,1)),
    ppe_face_mask NUMBER(1) DEFAULT 1 CHECK (ppe_face_mask IN (0,1)),
    ppe_other VARCHAR2(500),
    pfas_picograms_per_liter NUMBER(12,2),
    pfas_compound_tested VARCHAR2(30) CHECK (pfas_compound_tested IN ('PFOA','PFOS','PFNA','PFHxS','HFPO-DA','full_panel')),
    lab_notes CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT pfas_chain_custody_logic CHECK (
        (received_by_lab IS NOT NULL AND received_at_lab IS NOT NULL)
        OR (received_by_lab IS NULL AND received_at_lab IS NULL)
    )
);

CREATE INDEX idx_pfas_batch_sequence ON pfas_sampling(batch_id, sequence_number);

COMMENT ON TABLE pfas_sampling IS 'PFAS sampling with Chain of Custody and FRB/EB/TB sequencing per ODEQ 2026.';

-- ============================================================
-- 4. AUDIT LOGS TABLE
-- ============================================================
CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(100) NOT NULL,
    record_id NUMBER NOT NULL,
    action VARCHAR2(10) NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
    old_data CLOB CHECK (old_data IS JSON),
    new_data CLOB CHECK (new_data IS JSON),
    changed_by VARCHAR2(100) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500)
);

CREATE INDEX idx_audit_table_record ON audit_logs(table_name, record_id);
CREATE INDEX idx_audit_changed_at ON audit_logs(changed_at);

COMMENT ON TABLE audit_logs IS 'Immutable audit trail for all compliance-critical changes.';

-- ============================================================
-- 5. AUDIT TRIGGERS
-- ============================================================
CREATE OR REPLACE TRIGGER trg_audit_service_lines
AFTER INSERT OR UPDATE OR DELETE ON service_lines
FOR EACH ROW
DECLARE
    v_action     VARCHAR2(10);
    v_changed_by VARCHAR2(100) := COALESCE(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),'system');
    v_ip         VARCHAR2(45)  := SYS_CONTEXT('USERENV','IP_ADDRESS');
    v_old        CLOB;
    v_new        CLOB;
    v_id         NUMBER;
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT'; v_id := :NEW.id;
        v_new := JSON_OBJECT('id' VALUE :NEW.id, 'asset_id' VALUE :NEW.asset_id,
                   'system_owned' VALUE :NEW.system_owned, 'customer_owned' VALUE :NEW.customer_owned,
                   'service_line_material' VALUE :NEW.service_line_material,
                   'verified_status' VALUE :NEW.verified_status);
    ELSIF UPDATING THEN
        v_action := 'UPDATE'; v_id := :NEW.id;
        v_old := JSON_OBJECT('id' VALUE :OLD.id, 'asset_id' VALUE :OLD.asset_id,
                   'verified_status' VALUE :OLD.verified_status);
        v_new := JSON_OBJECT('id' VALUE :NEW.id, 'asset_id' VALUE :NEW.asset_id,
                   'verified_status' VALUE :NEW.verified_status);
    ELSIF DELETING THEN
        v_action := 'DELETE'; v_id := :OLD.id;
        v_old := JSON_OBJECT('id' VALUE :OLD.id, 'asset_id' VALUE :OLD.asset_id);
    END IF;
    INSERT INTO audit_logs(table_name,record_id,action,old_data,new_data,changed_by,ip_address)
    VALUES('SERVICE_LINES',v_id,v_action,v_old,v_new,v_changed_by,v_ip);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_evidence
AFTER INSERT OR UPDATE OR DELETE ON evidence
FOR EACH ROW
DECLARE
    v_action     VARCHAR2(10);
    v_changed_by VARCHAR2(100) := COALESCE(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),'system');
    v_ip         VARCHAR2(45)  := SYS_CONTEXT('USERENV','IP_ADDRESS');
    v_old        CLOB;
    v_new        CLOB;
    v_id         NUMBER;
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT'; v_id := :NEW.id;
        v_new := JSON_OBJECT('id' VALUE :NEW.id, 'service_line_id' VALUE :NEW.service_line_id,
                   'evidence_type' VALUE :NEW.evidence_type,
                   'gps_accuracy_meters' VALUE :NEW.gps_accuracy_meters);
    ELSIF UPDATING THEN
        v_action := 'UPDATE'; v_id := :NEW.id;
        v_old := JSON_OBJECT('id' VALUE :OLD.id, 'evidence_type' VALUE :OLD.evidence_type);
        v_new := JSON_OBJECT('id' VALUE :NEW.id, 'evidence_type' VALUE :NEW.evidence_type);
    ELSIF DELETING THEN
        v_action := 'DELETE'; v_id := :OLD.id;
        v_old := JSON_OBJECT('id' VALUE :OLD.id, 'service_line_id' VALUE :OLD.service_line_id);
    END IF;
    INSERT INTO audit_logs(table_name,record_id,action,old_data,new_data,changed_by,ip_address)
    VALUES('EVIDENCE',v_id,v_action,v_old,v_new,v_changed_by,v_ip);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_pfas_sampling
AFTER INSERT OR UPDATE OR DELETE ON pfas_sampling
FOR EACH ROW
DECLARE
    v_action     VARCHAR2(10);
    v_changed_by VARCHAR2(100) := COALESCE(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),'system');
    v_ip         VARCHAR2(45)  := SYS_CONTEXT('USERENV','IP_ADDRESS');
    v_old        CLOB;
    v_new        CLOB;
    v_id         NUMBER;
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT'; v_id := :NEW.id;
        v_new := JSON_OBJECT('id' VALUE :NEW.id, 'sample_id' VALUE :NEW.sample_id,
                   'sample_type' VALUE :NEW.sample_type, 'batch_id' VALUE :NEW.batch_id);
    ELSIF UPDATING THEN
        v_action := 'UPDATE'; v_id := :NEW.id;
        v_old := JSON_OBJECT('id' VALUE :OLD.id, 'sample_id' VALUE :OLD.sample_id);
        v_new := JSON_OBJECT('id' VALUE :NEW.id, 'sample_id' VALUE :NEW.sample_id);
    ELSIF DELETING THEN
        v_action := 'DELETE'; v_id := :OLD.id;
        v_old := JSON_OBJECT('id' VALUE :OLD.id, 'sample_id' VALUE :OLD.sample_id);
    END IF;
    INSERT INTO audit_logs(table_name,record_id,action,old_data,new_data,changed_by,ip_address)
    VALUES('PFAS_SAMPLING',v_id,v_action,v_old,v_new,v_changed_by,v_ip);
END;
/

-- ============================================================
-- 6. VERIFICATION STATUS TRIGGER
-- ============================================================
CREATE OR REPLACE TRIGGER trg_enforce_verified_status
BEFORE INSERT OR UPDATE ON service_lines
FOR EACH ROW
DECLARE
    v_has_photo  NUMBER := 0;
    v_has_frb    NUMBER := 0;
    v_mat_ok     NUMBER := 0;
    v_composite  VARCHAR2(50);
BEGIN
    v_composite := CASE
        WHEN :NEW.system_owned = 1 AND :NEW.service_line_material = 'lead' THEN 'System_Lead'
        WHEN :NEW.customer_owned = 1 AND :NEW.customer_side_material = 'lead' THEN 'Customer_Lead'
        WHEN :NEW.system_owned = 1 AND :NEW.service_line_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
        WHEN :NEW.customer_owned = 1 AND :NEW.customer_side_material = 'galvanized_requiring_replacement' THEN 'Galvanized_Requiring_Replacement'
        ELSE 'Non-Lead_Or_Unknown'
    END;

    IF :NEW.id IS NOT NULL THEN
        SELECT COUNT(*) INTO v_has_photo FROM evidence
        WHERE service_line_id = :NEW.id AND evidence_type = 'photo'
        AND gps_accuracy_meters <= 2 AND ROWNUM = 1;

        IF v_composite IN ('System_Lead','Customer_Lead','Galvanized_Requiring_Replacement') THEN
            SELECT COUNT(*) INTO v_has_frb FROM pfas_sampling
            WHERE service_line_id = :NEW.id AND sample_type = 'FRB'
            AND received_by_lab IS NOT NULL AND ROWNUM = 1;
        ELSE
            v_has_frb := 1;
        END IF;
    ELSE
        v_has_frb := 1;
    END IF;

    IF :NEW.system_owned = 0 OR NVL(:NEW.service_line_material,'unknown') != 'unknown' THEN
        v_mat_ok := 1;
    END IF;

    IF v_has_photo = 1 AND v_has_frb = 1 AND v_mat_ok = 1 THEN
        :NEW.verified_status := 1;
        :NEW.verified_at := SYSTIMESTAMP;
    ELSE
        :NEW.verified_status := 0;
        :NEW.verified_at := NULL;
        :NEW.verified_by := NULL;
    END IF;

    :NEW.last_updated := SYSTIMESTAMP;
END;
/

-- ============================================================
-- 7. PFAS SEQUENCE ORDER TRIGGER
-- ============================================================
CREATE OR REPLACE TRIGGER trg_check_pfas_sequence_order
BEFORE INSERT OR UPDATE ON pfas_sampling
FOR EACH ROW
DECLARE
    v_has_regular NUMBER := 0;
BEGIN
    IF :NEW.batch_id IS NOT NULL AND :NEW.sample_type IN ('FRB','EB','TB') THEN
        SELECT COUNT(*) INTO v_has_regular FROM pfas_sampling
        WHERE batch_id = :NEW.batch_id AND sample_type = 'regular'
        AND sequence_number < :NEW.sequence_number AND ROWNUM = 1;

        IF v_has_regular = 1 THEN
            RAISE_APPLICATION_ERROR(-20001,
                'FRB, EB, or TB must precede regular samples in sequence order per ODEQ 2026');
        END IF;
    END IF;
END;
/

-- ============================================================
-- 8. ORACLE SPATIAL METADATA (must come before spatial index)
-- ============================================================
INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES (
    'EVIDENCE', 'GPS_LOCATION',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.0000001),
        SDO_DIM_ELEMENT('Latitude',  -90,   90, 0.0000001)
    ),
    4326
);
COMMIT;

CREATE INDEX idx_evidence_gps ON evidence(gps_location)
    INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

-- ============================================================
-- 9. COMPOSITE INDEXES
-- ============================================================
CREATE INDEX idx_service_lines_composite ON service_lines(composite_classification, verified_status);

-- ============================================================
-- 10. HELPER FUNCTION
-- ============================================================
CREATE OR REPLACE FUNCTION make_gps_point(lon IN NUMBER, lat IN NUMBER)
RETURN SDO_GEOMETRY DETERMINISTIC IS
BEGIN
    RETURN SDO_GEOMETRY(2001, 4326, SDO_POINT_TYPE(lon, lat, NULL), NULL, NULL);
END;
/

-- Verify tables created
SELECT table_name FROM user_tables ORDER BY table_name;

EXIT;
